### ISSUE TITLE
Discussion: Which IDE to teach?

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/cog-flow-intro#9]
VS Code, only GitHub, only terminal, RStudio, Jupyter...?

**Comment by signekb** [comment]
@lwjohnst86 
Since we're only focussing on Markdown (i.e., no R or Python), it might make sense to just use VSCode (instead of Rstudio)? We also have great experiences using VSCode, so why not?

I think that only terminal will be too technical (at least most people are a bit scared of the terminal in the beginning - and this should not be the focus of the course). 

I have also considered only GitHub, but then learners would miss the local vs. remote repository part of Git, and I think that's a core part of collaborating using Git/GitHub too.

**Comment by lwjohnst86** [comment]
I also thought of GitHub only, but yea, that local vs remote no longer becomes part of it. Could be a thing to consider though, since I don't know if VS Code would be a good choice either, even though I like it. But really depends on what other assumptions we make of the learners.

**Comment by signekb** [comment]
Very true. I'll park this for now until #29 is more fleshed out.

**Comment by lwjohnst86** [comment]
OOOOOOO, you know what, maybe VS Code would be a good choice, because you can actually use VS Code directly INSIDE GitHub!! https://github.dev/github/dev

**Comment by lwjohnst86** [comment]
Reduces the barrier even more, since we won't have to get them to install anything 😛

**Comment by signekb** [comment]
But wont that also skip learning about local vs remote repos (at least in practice)?

**Comment by lwjohnst86** [comment]
VS Code might be the best general tool to use for teaching, especially since we don't know what our intended audiences programming tools (if they have on) are. So I think a local install (the GitHub dev as a backup) is a good choice.

**Comment by signekb** [comment]
Agreed 👍

**Comment by signekb** [comment]
@lwjohnst86 Do we feel like we have made a decision on this now (i.e., this issue can be closed)?

**Comment by lwjohnst86** [comment]
Yes, I think so :grin: Eventually I'd like to have a decision post like we do in Seedcase, but I need to setup the repo for that first. And it's low priority.

**Comment by signekb** [comment]
@lwjohnst86 Do you mean a repo for rostools (i.e., generally for all courses) or for this specific course?

**Comment by lwjohnst86** [comment]
Yea, like another repo :relaxed:
